name: Test
on:
  pull_request:
  workflow_call:
permissions: {}
jobs:
  terraform-validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - ./account
          - ./app
          - ./assurance_testing
          - ./data_replication
          - ./monitoring/aws
          - ./monitoring/grafana
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
      - name: Terraform validate ${{ matrix.working-directory }}
        working-directory: ${{ matrix.working-directory }}
        run: |-
          terraform init -backend=false
          terraform validate
